"""init database models

Revision ID: 9e1912f58d10
Revises: 
Create Date: 2024-05-31 00:47:55.987602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1912f58d10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'MODEL', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('file', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file'], ['file.id'], name='fk_part_file_id_file'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historys_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['history'], ['history.id'], name='fk_historys_parts_history_history_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part'], ['part.id'], name='fk_historys_parts_part_part_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historys_parts')
    op.drop_table('part')
    op.drop_table('user')
    op.drop_table('history')
    op.drop_table('file')
    # ### end Alembic commands ###
